//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./test_types');
//HELPER FUNCTIONS AND STRUCTURES

var IThriftTestInterfaceThriftService_serviceInvoke_args = function(args) {
  this.json = null;
  if (args) {
    if (args.json !== undefined && args.json !== null) {
      this.json = args.json;
    }
  }
};
IThriftTestInterfaceThriftService_serviceInvoke_args.prototype = {};
IThriftTestInterfaceThriftService_serviceInvoke_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.json = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

IThriftTestInterfaceThriftService_serviceInvoke_args.prototype.write = function(output) {
  output.writeStructBegin('IThriftTestInterfaceThriftService_serviceInvoke_args');
  if (this.json !== null && this.json !== undefined) {
    output.writeFieldBegin('json', Thrift.Type.STRING, 1);
    output.writeString(this.json);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var IThriftTestInterfaceThriftService_serviceInvoke_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
IThriftTestInterfaceThriftService_serviceInvoke_result.prototype = {};
IThriftTestInterfaceThriftService_serviceInvoke_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

IThriftTestInterfaceThriftService_serviceInvoke_result.prototype.write = function(output) {
  output.writeStructBegin('IThriftTestInterfaceThriftService_serviceInvoke_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var IThriftTestInterfaceThriftService_string2Int_args = function(args) {
  this.param = null;
  if (args) {
    if (args.param !== undefined && args.param !== null) {
      this.param = args.param;
    }
  }
};
IThriftTestInterfaceThriftService_string2Int_args.prototype = {};
IThriftTestInterfaceThriftService_string2Int_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.param = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

IThriftTestInterfaceThriftService_string2Int_args.prototype.write = function(output) {
  output.writeStructBegin('IThriftTestInterfaceThriftService_string2Int_args');
  if (this.param !== null && this.param !== undefined) {
    output.writeFieldBegin('param', Thrift.Type.STRING, 1);
    output.writeString(this.param);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var IThriftTestInterfaceThriftService_string2Int_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
IThriftTestInterfaceThriftService_string2Int_result.prototype = {};
IThriftTestInterfaceThriftService_string2Int_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

IThriftTestInterfaceThriftService_string2Int_result.prototype.write = function(output) {
  output.writeStructBegin('IThriftTestInterfaceThriftService_string2Int_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var IThriftTestInterfaceThriftServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
IThriftTestInterfaceThriftServiceClient.prototype = {};
IThriftTestInterfaceThriftServiceClient.prototype.seqid = function() { return this._seqid; };
IThriftTestInterfaceThriftServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
IThriftTestInterfaceThriftServiceClient.prototype.serviceInvoke = function(json, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_serviceInvoke(json);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_serviceInvoke(json);
  }
};

IThriftTestInterfaceThriftServiceClient.prototype.send_serviceInvoke = function(json) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('serviceInvoke', Thrift.MessageType.CALL, this.seqid());
  var args = new IThriftTestInterfaceThriftService_serviceInvoke_args();
  args.json = json;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

IThriftTestInterfaceThriftServiceClient.prototype.recv_serviceInvoke = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new IThriftTestInterfaceThriftService_serviceInvoke_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('serviceInvoke failed: unknown result');
};
IThriftTestInterfaceThriftServiceClient.prototype.string2Int = function(param, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_string2Int(param);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_string2Int(param);
  }
};

IThriftTestInterfaceThriftServiceClient.prototype.send_string2Int = function(param) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('string2Int', Thrift.MessageType.CALL, this.seqid());
  var args = new IThriftTestInterfaceThriftService_string2Int_args();
  args.param = param;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

IThriftTestInterfaceThriftServiceClient.prototype.recv_string2Int = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new IThriftTestInterfaceThriftService_string2Int_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('string2Int failed: unknown result');
};
var IThriftTestInterfaceThriftServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
IThriftTestInterfaceThriftServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
IThriftTestInterfaceThriftServiceProcessor.prototype.process_serviceInvoke = function(seqid, input, output) {
  var args = new IThriftTestInterfaceThriftService_serviceInvoke_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.serviceInvoke.length === 1) {
    Q.fcall(this._handler.serviceInvoke, args.json)
      .then(function(result) {
        var result_obj = new IThriftTestInterfaceThriftService_serviceInvoke_result({success: result});
        output.writeMessageBegin("serviceInvoke", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("serviceInvoke", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.serviceInvoke(args.json, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new IThriftTestInterfaceThriftService_serviceInvoke_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("serviceInvoke", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("serviceInvoke", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
IThriftTestInterfaceThriftServiceProcessor.prototype.process_string2Int = function(seqid, input, output) {
  var args = new IThriftTestInterfaceThriftService_string2Int_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.string2Int.length === 1) {
    Q.fcall(this._handler.string2Int, args.param)
      .then(function(result) {
        var result_obj = new IThriftTestInterfaceThriftService_string2Int_result({success: result});
        output.writeMessageBegin("string2Int", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("string2Int", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.string2Int(args.param, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new IThriftTestInterfaceThriftService_string2Int_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("string2Int", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("string2Int", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
